### ISSUE TITLE
autoStart and config file

### ISSUE THREAD

**Issue by jhoepffner** [Hemisphere-Project/HPlayer#32]
Hello,
I installed Player on 2 RPi (1A & 2B), it works very well on 2B. Before to continue, I need to know:
– how to auto start Player at boot ? I had try to put (the command working in ssh)
HPlayer/HPlayer --path /home/pi/Videos --start 1 --loop 1 --info 0 --ahdmi 1  --out 1234 --host 192.168.1.10
in a new file in /etc/cron.d, not working
in /etc/rc.local, not working
Any idea how to do it?
– to quit I use OSC with the address /quit, there is a way to do it in SSH?
– how to write inside data/settings.xml the settings I need at startup?
Thank you for your work, I will use it for a future installation.
Jacques Hoepffner

**Comment by Maigre** [comment]
Hi Jacques,

-- AUTOSTART --
to start HPlayer on boot i use /etc/rc.local 
but you need to provide an absolute path to the binary:
```
/home/pi/HPlayer/HPlayer --path /home/pi/Videos --start 1 --loop 1 --info 0 --ahdmi 1 --out 1234 --host 192.168.1.10
```

Beware that the default last line of /etc/rc.local is generally "exit 0"
so you must put your command before this exit command. If you put it after, the rc.local
script will return before executing your command.

Also it is recommanded to launch the player without blocking the rc.local script 
by detaching the player. To achieve that, add the & symbol at the end of your command like this:
```
/home/pi/HPlayer/HPlayer --path /home/pi/Videos --start 1 --loop 1 --info 0 --ahdmi 1 --out 1234 --host 192.168.1.10 &
```

For more conveniance, you could:
1. Create a launch script with all the parameters:
```
nano ~/startplayer.sh

#### PUT THIS:
#!/bin/sh
/home/pi/HPlayer/HPlayer --path /home/pi/Videos --start 1 --loop 1 --info 0 --ahdmi 1 --out 1234 --host 192.168.1.10
#### SAVE AND CLOSE with CTRL-X

chmod +x ~/startplayer.sh
```
2. Check the proper execution
```
/home/pi/startplayer.sh
```
You can exit with CTRL+C

3. Add it to rc.local
```
sudo nano /etc/rc.local

#### PUT THIS before "exit 0"
/home/pi/startplayer.sh &
#### SAVE AND CLOSE with CTRL-X
```

4. Reboot and it should work
```
sudo reboot
```

-- QUIT --
To exit the player when you started it from SSH you can use CTRL+C if the player is playing something. There is a bug that prevent the player to exit with CTRL+C when the player is doing nothing, i will fix that in a futur version. 
If you cannot exit with CTRL+C because of this bug, or because the player has been started automatically at boot, what i suggest is to SSH to the Pi in a different terminal,
and execute this command:
```
sudo pkill HPlayer 
```
adding -9 at the end of the command might help

-- CONFIG --
the /home/pi/HPlayer/data/settings.xml is created with default values the first time you start 
the player. You can then edit it with 
```
nano /home/pi/HPlayer/data/settings.xml
```
or by putting the SD Card in your computer and editing the file on your computer.

The settings you'll put there are gonna be applied automatically but if you provide
command line settings (like --ahdmi 1) they will overwrite the settings.xml parameters.
So if everything is properly set in settings.xml file, you don't need to provide
command line arguments to start the player: /home/pi/HPlayer/HPlayer should be enough.
It's you choice to use either command line arguments (you can put it in a script for more
conveniance like exposed earlier) or to use the settings.xml for main settings.

The settings.xml is also useful to achieve command mapping, when you can not customize the software that send OSC to the player. In settings.xml you can map a fixed osc command like "/button1" to a given player command like "/stop". The player will interpret any "/button1" received as a stop.

Let me know if some of those explaination are not clear.
And thanks for using HPlayer :)

Best,

**Comment by jhoepffner** [comment]
Thank you for the quick answer…
– I made mistake on path and on chmod and now
/home/pi/startplayer.sh
is playing properly but writing it in /etc/rc.local doesn't works at startup.
I tried also inside /etc/cron.d/autostart no better. I continue to search.
– ctrl+q works sometimes and pkill with another terminal window ever
– setting.xml works for the setting but how to declare a specific media, not a path?… It's not a problem for me, the commands come from Isadora and I can personalize the OSC flow
– zoom is working for .jpg but not for .mov (no problem for me)
– blur is not working at all

What should be great would be to have the possibility to fade the image, any possibility?
Anyway, great app and very useful replacement for the 6 Blu-ray player I bought last year, with here the possibility to sync the starts.

Thank you,
Jacques

**Comment by Maigre** [comment]
Hi, 
sorry for the delayed response, 
i'll answer as a reference for others.

- you can't specify a media in settings.xml but you can specify it as argument at HPlayer launch. In your  startplayer.sh script add --media /path/to/media after HPlayer command

- in order to use zoom with video you must add --gl 1 arguments at startup  (or in settings.xml) 
but it will soon become the default setting

- blur seems broken indeed. Last OF seems to break RPi shaders support.
I'll investigate that issue

Best Regards,
Thomas
